language: node_js
notifications:
  email: false
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install --save-dev @wojtekmaj/enzyme-adapter-react-17
script:
  - npm test -- --coverage
